/*******************************************************************************
* Copyright 2015, The IKANOW Open Source Project.
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License, version 3,
* as published by the Free Software Foundation.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
******************************************************************************/
package com.ikanow.aleph2.management_db.module;

import java.util.Arrays;

import org.checkerframework.checker.nullness.qual.Nullable;

import com.google.inject.AbstractModule;
import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Scopes;
import com.google.inject.name.Named;
import com.google.inject.name.Names;
import com.ikanow.aleph2.data_model.interfaces.data_services.IManagementDbService;
import com.ikanow.aleph2.management_db.services.CoreManagementDbService;

import fj.data.Either;
import fj.data.List;

/** Module enabling the management_db_service to be run standalone for testing purposes
 * @author acp
 */
public class StandaloneManagementDbModule extends AbstractModule {

	//TODO (ALEPH-19): This is the "old" style of doing things, update to the nicer way once the data_model has been updated
	
	// (will have one of these 2 only)
	protected IManagementDbService _management_db_service;
	protected Injector _injector;
	
	/** Gets the injector generated by a call to the user constructor
	 * @return the guice injector
	 */
	@Nullable
	public Injector getInjector() {
		return _injector;
	}
	
	/** Default c'tor called by Guice
	 * @param management_db_service - the injected core management db service object
	 */
	@Inject
	protected StandaloneManagementDbModule(final @Named("management_db_service_core") IManagementDbService management_db_service) {
		_management_db_service = management_db_service;
		
		//DEBUG
		//System.out.println("Hello world from: " + this.getClass() + ": management_db_service=" + management_db_service);		
	}

	protected String _underlying_management_db_service_name = null;
	
	/** User constructor = to create a standalone app based on this service
	 * @param modules - first one is the underlying service (eg com.ikanow.aleph2.management_db.mongodb.services.[Mock]MongoDbManagementDbService), then a list of additional modules to load (eg com.ikanow.aleph2.management_db.mongodb.module.[Mock]MongoDbManagementDbModule)
	 * @throws ClassNotFoundException 
	 * @throws IllegalAccessException 
	 * @throws InstantiationException 
	 */
	public StandaloneManagementDbModule(Either<String[], String> modulesOrServiceName) throws ClassNotFoundException, InstantiationException, IllegalAccessException {
		if (modulesOrServiceName.isLeft()) {
			
			Iterable<Module> list = List.<String>iterableList(Arrays.asList(modulesOrServiceName.left().value()))
													.drop(1)
													.map(m -> {
														try {
															return (Module)((Class.forName(m)).newInstance());
														}
														catch (Exception e) { 
															throw new RuntimeException("Cast to module: " + m, e);
														}
													})
													.cons(new CoreManagementDbModule())
													.cons(new StandaloneManagementDbModule(Either.<String[], String>right(modulesOrServiceName.left().value()[0])))
													;
			
			_injector = Guice.createInjector(list);
			
			_injector.getInstance(StandaloneManagementDbModule.class);
		}
		else {
			_underlying_management_db_service_name = modulesOrServiceName.right().value();				
		}
	}

	/* (non-Javadoc)
	 * @see com.google.inject.AbstractModule#configure()
	 */
	@SuppressWarnings("unchecked")
	@Override
	protected void configure() {
		/**/
		System.out.println("HERE?! " + this + " : " + _underlying_management_db_service_name);
		
		// Load the core service:
		this.bind(IManagementDbService.class).annotatedWith(Names.named("management_db_service_core")).to(CoreManagementDbService.class).in(Scopes.SINGLETON);
		
		// Load the underlying service
		if (null != _underlying_management_db_service_name) { // (else )
			try {
				this.bind(IManagementDbService.class).annotatedWith(Names.named("management_db_service"))
						.to((Class<? extends IManagementDbService>) Class.forName(_underlying_management_db_service_name))
						.in(Scopes.SINGLETON);
						;
			} catch (ClassNotFoundException e) {
				throw new RuntimeException("No 'underlying' IManagementDbService defined: " + _underlying_management_db_service_name, e);
			}
		}			
	}
	
}
